name: Run Gradle on Commit
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    gradle:
        strategy:
            matrix:
                os: [ ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   run: git checkout HEAD^
            -   uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-version: release-candidate

            -   name: Execute Gradle build
                run: gradle -x test build
